"""empty message

Revision ID: 51e24e66bda4
Revises: fcaaf0d024a5
Create Date: 2024-03-22 19:06:47.140522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e24e66bda4'
down_revision = 'fcaaf0d024a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relation', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('relation')

    # ### end Alembic commands ###
